@url = http://localHost:3010/api/v1

@menuId = 67462e91569f6361e1377767
@eventId = 6757e5beee4de52a7c7e3733

### Check All Menu Items
GET {{url}}/Menu/

### Check For Menu Item ID
GET {{url}}/Menu/{{menuId}}

### Add Menu Item
POST {{url}}/Menu/
Content-Type: application/json

{
    "Name":"TEST",
    "Description":"TEST",
    "Price":"January 1st, 9999",
    "Number":"6:66pm"
}



### Check for all Events
GET {{url}}/Events/

### Check for Events ID
GET {{url}}/Events/{{eventId}}

### Add Events
POST {{url}}/Events/
Content-Type: application/json

{
    "Name":"TEST",
    "Location":"TEST",
    "Date":"January 1st, 9999",
    "Time":"6:66pm",
    "ID":"0"
}
